### ISSUE TITLE
Add newer versions of GCC to the Travis CI build

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/vcf-validator#106]
The versions of GCC used in the Travis CI build are not ancient but they are not new either. New versions include more checks and would also support features from the latest versions of the C++ language.

Add new environment configurations to the `.travis.yml` file to use these more modern versions of the compiler, and fix any compile/test issues that could arise.

**Comment by jmmut** [comment]
given that newer versions were added but the gcc 7 was agreed not to be included because it was too slow, we can close this.
