### ISSUE TITLE
src/vcf/main.cpp:98:21: error: cannot convert ‘std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}’

### ISSUE THREAD

**Issue by kaihendry** [EBIvariation/vcf-validator#11]
http://ix.io/l0w

**Comment by cyenyxe** [comment]
Thanks for reporting. The most probable reason seems to be that GCC 5.0 now (correctly) reports this as an error, but previous versions didn't: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66365

I use GCC 4.8, so unfortunately didn't catch it. Could you please confirm your compiler version? Thanks!

**Comment by kaihendry** [comment]
gcc (GCC) 5.2.0

**Comment by cyenyxe** [comment]
It should be fixed now in the "develop" branch. Could you please try to compile it again?
