### ISSUE TITLE
No error/warning for missing symbolic alternate allele description in header

### ISSUE THREAD

**Issue by eroller** [EBIvariation/vcf-validator#112]
I had a file with entries that had ALT column `<DUP>` but that ALT did not have a description in the vcf header. vcf-validator didn't generate an error or warning for this file. I looked in the vcf spec and didn't see this as a requirement, but perhaps vcf-validator should generate a warning for it?

**Comment by eroller** [comment]
My mistake. I did get a warning for this scenario:

Line 199: Alternate '<DUP>' is not listed in a valid meta-data ALT entry (warning)

**Comment by jmmut** [comment]
Yes, that is the expected behaviour. Glad you figured it out. Also, if this or any other part of the usage of the vcf-validator is unintuitive or hard to work with, please tell us.
