### ISSUE TITLE
 Some report types are not supported

### ISSUE THREAD

**Issue by hsiaoyi0504** [EBIvariation/vcf-validator#120]
When I use ` ./vcf_validator -i variants_F_updated.vcf -r database -o ./report/` it works normally. However, when I use `/vcf_validator -i variants_F_updated.vcf -r database,summary -o ./report/`, it reports that `Please use only valid report types`.

**Comment by hsiaoyi0504** [comment]
Sorry, I found that the current `develop` is not the same as latest release.

**Comment by jmmut** [comment]
Exactly. In the current stable release, all the available reports you can use are `-r database,text`. It seems having `develop` as main branch might be confusing. We'll put master as default branch, so that the README when you land the repository matches the precompiled binary in the releases tab.
