### ISSUE TITLE
Missing vcf-validator code from Dockerfile

### ISSUE THREAD

**Issue by loreseeker** [EBIvariation/vcf-validator#129]
Hi, just tried using the provided Dockerfile to build vcf-validator and I noticed that the actual vcf-validator github code doesn't seem to be included anywhere (unless I was doing something very wrong, no git or wget-ing of it occurs anywhere). 
Anyhow, just wanted to give you a heads up about this. I edited the Dockerfile somewhat and was able to build the apps. I'm attaching my current Dockerfile (ubuntu-based) if anyone's interested.

[Dockerfile.txt](https://github.com/EBIvariation/vcf-validator/files/1829233/Dockerfile.txt)

**Comment by Anishka0107** [comment]
Hi, the steps to do the docker build are given in https://github.com/EBIvariation/vcf-validator/blob/master/README.md#static-build-docker-based

Our Dockerfile just sets up the environment necessary for compiling vcf-validator (installing required stuff in the docker build) and the entrypoint.sh (which gets executed in the docker run command) actually compiles it.

You would have to clone the repo or download the source code as mentioned in the steps linked above.

**Comment by loreseeker** [comment]
Ah, sorry, I assumed it was a full Dockerfile. Thank you for clarifying.
