### ISSUE TITLE
Add stdout in report options

### ISSUE THREAD

**Issue by srbcheema1** [EBIvariation/vcf-validator#132]
Currently vcf-validator provides 3 options for the report
i.e. summary, text and database
We can provide an option for stdout also.
As it will be convenient for the user to see the output without opening a file.
It will be same as vcf-debugulator provides an option for giving output on stdout. We can provide same facility in vcf-validator also.

```
Allowed options:
  -r [ --report ] arg (=summary) Comma separated values for types of reports 
                                 (summary, text, database, stdout)

```

**Comment by srbcheema1** [comment]
I would like to work on it if it is good.

**Comment by jmmut** [comment]
ah, shame we didn't see this sooner, we had a 4-days weekend. Actually this is how the validator worked in the first versions. It's more comfortable for toy testing, but in real environments you always want to write to files, and want to keep the general logging clean of reports.

Having it as an extra report type might be useful sometimes but doesn't feel right, it's mixing report algorithms with output places. we also have the option -o, but that's only for the directory, and it would be used for all the reports except `-r stdout`, and stdout is not valid in -o. At the end it's just too confusing and no one will use it properly.

if @cyenyxe agrees, we have to reject this issue and PR, sorry.

**Comment by jmmut** [comment]
We actually did a survey that supported the idea of moving away from this functionality

**Comment by cyenyxe** [comment]
Agree with comments by @jmmut, sorry we didn't notice this earlier.
