### ISSUE TITLE
Does not fail when output folder does not have write permission

### ISSUE THREAD

**Issue by j-coll** [EBIvariation/vcf-validator#142]
I have executed the validator without specifying the `-o`, so as default uses the location of the input file, where I don't have write permissions. The program has not failed at any point.

```
jcoll@node-01:~$ ./vcf_validator_linux -i /data/my_vcf.vcf.gz
[info] Reading from input file...
[warning] Detected .gz compression
Lines read: 10000
Lines read: 20000
Lines read: 30000
....
....
Lines read: 130610000
Lines read: 130620000
Lines read: 130630000
[info] Summary report written to : /data/my_vcf.vcf.gz.errors_summary.1529575578873.txt
[info] According to the VCF specification, the input file is not valid
jcoll@node-01:~$ less /data/my_vcf.vcf.gz.errors_summary.1529575578873.txt
/data/my_vcf.vcf.gz.errors_summary.1529575578873.txt: No such file or directory
```

**Comment by jmmut** [comment]
This is merged in develop, but we will close when it's in a release and the requestor confirms it's fixed.

**Comment by jmmut** [comment]
I tested this with the latest release and it works as expected.

However, we can improve this message in the case of ODB report:

> ./vcf_validator_linux -i no_write_permissions/a.vcf  -r database
> [error] The validation could not be completed: ODB report: Can't initialize database: 14: unable to open database file

should say the path of the "database file"
