### ISSUE TITLE
No newline error at the end of the VCF

### ISSUE THREAD

**Issue by elowy01** [EBIvariation/vcf-validator#148]
Hi,

I am running the vcf-validator and it is considering a VCF as not valid and throwing the following error:

Error: There is no newline at the end of the file.

I had a look to the VCF and it seems to be correct, I think this could be caused by the Boost libraries that I think the validator uses. But I could be wrong.

Could you please help with this?

Thanks,

ernesto

**Comment by jmmut** [comment]
ok, can you show the last bytes of the file? something like `tail your_file.vcf | xxd`

**Comment by elowy01** [comment]
Hi,
I am using Linux

When I do:
 zcat input.vcf.gz | tail -n 5 | xxd

I get (showing only the last lines):
 00d4e0: 0930 7c30 0930 7c30 0930 7c30 0930 7c30  .0|0.0|0.0|0.0|0
000d4f0: 0930 7c30 0930 7c30 0930 7c30 0930 7c30  .0|0.0|0.0|0.0|0
000d500: 0930 7c30 0930 7c30 0930 7c30 0930 7c30  .0|0.0|0.0|0.0|0
000d510: 0930 7c30 0930 7c30 0930 7c30 0a         .0|0.0|0.0|0.

So it seems that the new line is there,

Thanks,

e

**Comment by jmmut** [comment]
well that's strange. We will need to debug more thoroughly. Why do you say it might be because of the boost library?

Also how big is the file? we took care to make the validator work with huge files and lots of samples, but there could still be some bug. Can you tell approximate number of samples and lines? or number of samples and file size if counting the lines would take too long

**Comment by srbcheema1** [comment]
@elowy01 could you please tell the command you are using to validate the file. And also please tell which version of vcf-validator are you using. 
Once try it after uncompressing it and then passing  to the validator.
`zcat input.vcf.gz | ./vcf_validator`
It would be nice if you could provide the results of using uncompressed file on [v0.7](https://github.com/EBIvariation/vcf-validator/releases/download/v0.7/vcf_validator) of the validator. That information will be helpful for us.

**Comment by elowy01** [comment]
Hi, 
I've had problems with other programs using Boost that did not read the last line of a compressed file. 
The VCF is not very big: 283M. Number of samples: 2698

**Comment by elowy01** [comment]
Hi,
I've tried using zcat input.vcf.gz |./vcf_validator and it works now,

So I guess that the issue I had is fixed by doing this, 

Thanks for your help,

e.
