### ISSUE TITLE
Incorrect complaint about GP format field in vcf 4.2

### ISSUE THREAD

**Issue by kscheffler** [EBIvariation/vcf-validator#149]
The GP format field is defined as a phred-scaled quantity (i.e. typically larger than 1) in vcf format 4.2 and as a probability between 0 and 1 in vcf format 4.3. However, vcf-validator (version 0.7) reports an error "value does not lie in the interval [0,1]" for vcf 4.2.

**Comment by tcezard** [comment]
Now tracked in EVA-2049: closing
