### ISSUE TITLE
Segmentation fault on empty vcf file.

### ISSUE THREAD

**Issue by srbcheema2** [EBIvariation/vcf-validator#154]
Whenever we try to pass an empty vcf file to vcf-validator it will cause segmentation fault.
The problem is with [std::equal(first.begin(), first.end(), second.begin())](https://en.cppreference.com/w/cpp/algorithm/equal) function while comparing two vectors the second one should have size more than the first vector.

Line of problem : [link](https://github.com/EBIvariation/vcf-validator/blob/5270a1170c2a030781ae515932746b2a03fbac10/src/vcf/validator.cpp#L251)

**Comment by srbcheema1** [comment]
We need to add a condition to check the size of `line`. It should not be lesser than 5.

**Comment by hritikgupta** [comment]
Please assign me the issue.

**Comment by cyenyxe** [comment]
Fixed via #156 and #161 .
