### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by srbcheema1** [EBIvariation/vcf-validator#157]
It seems like new contributors are facing problems due to the reason there is no `CONTRIBUTING.md` file in this repository.
for example they may face problem to understand that the main working branch to make a PR is `develop` not `master`.
There are many other issues that contributors face like issue of improper indentation.
There is need to add a `CONTRIBUTING.md` file to guide new-comers to get to know about the rules and ways to make commits and open a PR.

**Comment by hritikgupta** [comment]
+1

**Comment by cyenyxe** [comment]
Fixed via #158 .
