### ISSUE TITLE
Inconsistencies in header number/type not detected

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/vcf-validator#16]
The Number/Type of a field in the body must not only match those in the header, but the header itself must match the description from the VCF specification.

**Comment by jmmut** [comment]
Can we list some buggy behaviours?

**Comment by cyenyxe** [comment]
This applies to reserved fields only.

For instance, AF should be defined in the header as Number=A,Type=Float. But if the header said it is a Number=1,Type=String and the body matched that description, the validator wouldn't complain.

**Comment by jmmut** [comment]
done in #70, #72, #73
