### ISSUE TITLE
Warn if there were unused parameters

### ISSUE THREAD

**Issue by jmmut** [EBIvariation/vcf-validator#165]
In the (I hope) unlikely case that someone is using the parameters incorrectly and some parameters were not used, it would be nice to show a warning with the unused parameters:

```
$ ./vcf_validator -i a.vcf -r summary, text
[warn] unused parameters: "text"
```

**Comment by srbcheema1** [comment]
could we also add one more check in `check_options` warning user if he provides multiple levels in single go, 
for example:
`$ ./vcf_validator -l error,stop,warning -i input.vcf`

**Comment by jmmut** [comment]
well, in the case of several levels, it shows `[error] Please choose one of the accepted validation levels` and aborts, so I think it's fine.
