### ISSUE TITLE
Ensure compressed FASTA files are handled properly

### ISSUE THREAD

**Issue by jmmut** [EBIvariation/vcf-validator#172]
I expect the assembly checker won't be able to use compressed FASTAs, even having the index file (.fai), so we have to manually check that it fails on compressed FASTAs and then put a check in the code to throw an exception if the FASTA is compressed, and stop the program with a clear error message.

Otherwise we will read rubbish and it will say 0% matches the reference, or not finding the contigs.

**Comment by tcezard** [comment]
This has been done as part of EVA-1731
