### ISSUE TITLE
Provide working Docker image for users

### ISSUE THREAD

**Issue by huguesfontenelle** [EBIvariation/vcf-validator#180]
Hello
From the documentation I read
```
3. Build the executable running docker run -v ${PWD}:/tmp ebivariation/vcf-validator. Again, replace ebivariation with your user name if necessary.
```
I infer from that line in the doc, that this image is for development, since it requires further compilation.

As a user, I would like a docker image, preferably hosted on dockerhub. Then I could run:
```
docker run -v ${PWD}:/tmp ebivariation/vcf-validator vcf-validator -i /path/to/file.vcf
```
Please have a look at http://biocontainers.pro/docs/101/running-example/ for inspiration.
By the way, a recipe for [biocontainers](https://biocontainers.pro/) would be really good for adoption, as well as [bioconda](https://bioconda.github.io/) recipes 

Note that, at the moment (`master:cdbdb19`), the compilation fails with:
```
make[2]: *** [CMakeFiles/mod_vcf.dir/src/fasta/fasta.cpp.o] Error 1
In file included from /tmp/inc/fasta/fasta.hpp:26:0,
                 from /tmp/inc/vcf/assembly_checker.hpp:34,
                 from /tmp/src/vcf/assembly_checker.cpp:17:
/tmp/inc/util/curl_easy.hpp:23:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
```

**Comment by jmmut** [comment]
ok, we added recently the dependency for curl, so we definitely have to fix that, thanks for noticing.

In the meantime, I would like to make sure you are aware that you don't need docker at all to run our tools. You can download the binary(ies) from https://github.com/EBIvariation/vcf-validator/releases and use it directly as `./vcf-validator -i /path/to/file.vcf`.

**Comment by huguesfontenelle** [comment]
Thanks! Pretty cool tool :-)

**Comment by jmmut** [comment]
Thanks! Regarding the other point, after confirming it with the team, in the future we might think again about publishing the image in biocontainers or bioconda, but for now it won't happen any time soon. We hope downloading the binary (without any other requirement or dependency) is easy enough.
