### ISSUE TITLE
INFO and SAMPLE floating point fields range is not checked

### ISSUE THREAD

**Issue by cyenyxe** [EBIvariation/vcf-validator#19]
Some integer number fields are checked to guarantee their zero or positive, but this doesn't happen for floating-point fields. Also, those fields that represent frequencies are not checked to be between 0 and 1.

This fix will involve un-commenting the test file `failed_body_info_004.vcf`.

**Comment by jmmut** [comment]
There are some fields like GL that are logarithms of frequencies, so its range is (-inf, 0], and this range is not described in the meta entry of the field, so we can only do range checks for the reserved fields described in the spec.

**Comment by jmmut** [comment]
done partially in #72. except for some fields that are not unambiguously specified (https://github.com/samtools/hts-specs/issues/224 and the ones about likelihood such as PL or GL)

**Comment by Anishka0107** [comment]
Done partly in https://github.com/EBIvariation/vcf-validator/pull/89

**Comment by jmmut** [comment]
another bug: FORMAT GP in 4.2 is not a probability [0, 1] as in 4.3, it's a phred-scale (https://genome.sph.umich.edu/wiki/Phred_scale) which I think it's [0, +inf)

**Comment by tcezard** [comment]
Tracked in EVA-2051: closing

**Comment by tcezard** [comment]
tracked in EVA-2052: closing
