### ISSUE TITLE
vcf_validator.exe fails 

### ISSUE THREAD

**Issue by mrpk123** [EBIvariation/vcf-validator#200]
Hi,

This may not be an issue. I need your help to make vcf_validator.exe running.
I downloaded the latest exe for Windows. I tried running it however got following error.

![error](https://user-images.githubusercontent.com/50906245/78745758-b2c22a00-7982-11ea-9fb3-f762fb214384.jpg)

My OS is Windows 10. Do i need to install any applications manually? I have assumed that running exe would be suffice. 
Thanks in advance for your help.

**Comment by jmmut** [comment]
thanks for telling us. This error is not expected, you shouldn't need to install anything. We'll look into this but I can not give any timeline. Did you try previous versions? https://github.com/EBIvariation/vcf-validator/releases

**Comment by jmmut** [comment]
oh, I forgot, that library can not be bundled in the validator in windows. please download the dll [here](https://github.com/EBIvariation/vcf-validator/tree/master/lib/windows_specific) and put them in the same folder as the vcf-validator.exe.

**Comment by mrpk123** [comment]
Hi jmmut,

Thank you for your prompt response. I have downloaded the files and copied in the same folder as that of the exe. Although the execution proceeds further, I am getting a new error :
![entry_point_error](https://user-images.githubusercontent.com/50906245/78857836-1f532c80-7a48-11ea-89e1-36af5032c933.jpg)

Is it related to code or to my system setup?

Thanks in advance for your help

**Comment by mrpk123** [comment]
Hi jmmut,

Please ignore my last message. It was my bad. I had not copied the files properly.
Now its working. I have tried on one vcf file and the execution completed successfully :)

Thanks so much for your help

**Comment by jmmut** [comment]
Glad it worked for you! I added a sentence explaining this in the "Download" section of the readme for future users.
Thanks again for the feedback.
