### ISSUE TITLE
Is underscore not allowed to be used?

### ISSUE THREAD

**Issue by htchihiro** [EBIvariation/vcf-validator#207]
Hi,

When validating my vcf file using vcf_validator, I am getting an error message.

Error message:
According to the VCF specification, the input file is not valid
Error: Format is not a colon-separated list of alphanumeric strings. This occurs 34 time(s), first time in line 41.

line 40 - 42 in my vcf file
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	NA12891
demo20	1	.	T	.	.	LowGQX	END=899;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	.:.:0:0:0
demo20	900	.	G	.	.	LowGQX;LowDepth	END=906;BLOCKAVG_min30p3a	GT:GQX:DP:DPF:MIN_DP	0/0:5:2:0:2

I removed underscore"_" from BLOCKAVG_min30p3a and MIN_DP.
My vcf file passed the validation.

If we can't use underscore, we hope it can. This is because many VCF-creating tools include underscores.
Could you please check it?

**Comment by tcezard** [comment]
Hi @htchihiro 
Could you specify which version of the VCF format you are using ? 
underscores were not allowed in [version 4.2](https://github.com/samtools/hts-specs/blob/master/VCFv4.2.pdf) (see section 1.4.2) but are now allowed in [version 4.3](https://github.com/samtools/hts-specs/blob/master/VCFv4.3.pdf) (section 1.6.2)

Does this explain your issue ?

**Comment by htchihiro** [comment]
Thanks for the answer and the important information.

I used vcf version 4.1. I will update the vcf version.
I understand that this validator checks the vcf version and changes the validation rules according to that version, is that correct?

**Comment by tcezard** [comment]
Yes this is correct.
