### ISSUE TITLE
Error to validate vcf file from stacks (gstack tools reference mapping) 

### ISSUE THREAD

**Issue by FranciscoAscue** [EBIvariation/vcf-validator#218]
I worked with [stacks2](https://catchenlab.life.illinois.edu/stacks/manual/), and I want to submit this data to EBI I have the following errors after applying vcf_validator_linux and vcf_debugulator_linux:
```
According to the VCF specification, the input file is not valid
Error: Sample #5, field GL does not match the meta specification Number=G (expected 3 value(s)). This occurs 1842 time(s), first time in line 3160.
Warning: A valid 'reference' entry is not listed in the meta section. This occurs 1 time(s), first time in line 3160.
Error: Sample #7, field GL does not match the meta specification Number=G (expected 3 value(s)). This occurs 1107 time(s), first time in line 3161.
Error: Sample #3, field GL does not match the meta specification Number=G (expected 3 value(s)). This occurs 1509 time(s), first time in line 3162.
.
.
.
```

I Don't Know if the useful tools for handling VCF files that recommend on the EBI submissions help page are mandatory because Stacks generate VCF files directly. Any insight about the error above is helpful for us.

PD. 

I worked with 40 individuals of Cavia Porcellus from RAD-seq sequencing and use the Scaffolds genome as reference ([cavpor3](https://www.ncbi.nlm.nih.gov/assembly/GCF_000151735.1/))

**Comment by tcezard** [comment]
The GL field is supposed to contain Genotype likelihood. for a diploid individual there should be 3 values for 3 possible genotypes (AA/AB/BB). My guess is that [stacks](https://catchenlab.life.illinois.edu/stacks/manual/) outputs something slightly different overloading the GL field. That makes the field incompatible with downstream tools and the VCF specification. 
You can remove the GL field from the VCF file with bcftools 
```
bcftools annotate -x FORMAT/GL file.vcf.gz
```
