### ISSUE TITLE
v0.9.5 Linux binaries display version 0.9.4 with '-v' option

### ISSUE THREAD

**Issue by gg78uol** [EBIvariation/vcf-validator#236]
The 0.9.5 Linux binaries do not display the correct version with the -v flag. To reproduce:

wget https://github.com/EBIvariation/vcf-validator/releases/download/v0.9.5/vcf_assembly_checker_linux
wget https://github.com/EBIvariation/vcf-validator/releases/download/v0.9.5/vcf_debugulator_linux
wget https://github.com/EBIvariation/vcf-validator/releases/download/v0.9.5/vcf_validator_linux
chmod +x vcf_*

./vcf_validator_linux -v
	vcf_validator version 0.9.4

./vcf_assembly_checker_linux -v
	vcf-assembly-checker version 0.9.4

./vcf_debugulator_linux -v
	vcf-debugulator version 0.9.4

**Comment by tcezard** [comment]
Thank you for the report. This has been fixed in version [v0.9.6](https://github.com/EBIvariation/vcf-validator/releases/tag/v0.9.6)
