### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by DKPOWA** [EBIvariation/vcf-validator#40]
Hi,

Im running 

> Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux

While installing, after getting the libraries needed, going cmake this happens:

> Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!

I tried searching but google didnt provide any useful solution, I hope you can.

Kinds regards,
Maxi

**Comment by cyenyxe** [comment]
Just to confirm, is that error raised while running `cmake`, not even during compilation with `make`? In that case, it would have nothing to do with the application code, but with the environment.

Which version of Debian and cmake do you have installed?

**Comment by cyenyxe** [comment]
No reply received in 2 months. Please re-open the ticket if the issue persists.
