### ISSUE TITLE
Info CIGAR value is not an alphanumeric string compliant with the SAM specification

### ISSUE THREAD

**Issue by sambrightman** [EBIvariation/vcf-validator#56]
INFO CIGAR is marked as `Number=A` and contains commas. The current regex is `([0-9]+[MIDNSHPX])+`. Perhaps this should be `[0-9]+[MIDNSHPX](,[0-9]+[MIDNSHPX])+`?

**Comment by cyenyxe** [comment]
Yes, it should accept multiple values as the spec describes it as

> CIGAR : cigar string describing how to align an alternate allele to the reference allele

The existing regex still applies to single values, because it needs to match patterns like `100M` and `10M3I2D`. If I get this correctly and split in two rules, it would look like the following:

> cigar_value = ([0-9]+[MIDNSHPX])+
> cigar = cigar_value ( , cigar_value )*

**Comment by sambrightman** [comment]
Quite right, yes. Had stab at it in linked PR.
