### ISSUE TITLE
Not all warnings are tested

### ISSUE THREAD

**Issue by Anishka0107** [EBIvariation/vcf-validator#92]
Add tests for warnings

**Comment by jmmut** [comment]
@srbcheema1, are you going to add more tests? As there are several students contributing, it would be good to know if someone is working on an issue, so that no effort is wasted, and this issue has still room for more improvements.

**Comment by srbcheema1** [comment]
I am still working on it.
I was just slow due to some academic work pressure in past few days. I will be soon updating the PR

**Comment by jmmut** [comment]
no hurries! just asking

**Comment by srbcheema1** [comment]
I was stuck somewhere on reading compressed file issue. I sent you the problem and its available solution. please have a look.

**Comment by tcezard** [comment]
Tracked in EVA-2053: closing
