### ISSUE TITLE
EVA-408 Benchmarking for different file profiles

### ISSUE THREAD

**Issue by jmmut** [EBIvariation/vcf-validator#93]
In order to detect bottlenecks in the code, performance needs to be evaluated for different cases, such as the following.

Fully valid files:

 -   Aggregated file with as many missing fields as possible
 -   Aggregated VCF file
 -   Genotyped VCF file
-    Long files (lots of variants)
-    Wide files (lots of samples)

Incorrect files:

-    With same syntax error in every line
-    With same semantic error in every line
-    With same syntax error in 50% of the lines
-    With same semantic error in 50% of the lines

**Comment by tcezard** [comment]
This is tracked in EVA-408 already: closing
